logd_integration_test: failure includes stats
This test was failing in a few presubmit runs, and it was
very unclear what was causing it. Now, we include the full
statistics in the output, which should allow most failures to
be trivially traiged.

Bug: N/A
Test: make sure failure has stats, e.g.:

     AssertionError: 9844 not less than or equal to 4000 : Buffer main has 9844 dropped logs (now 15815 out of 25659 total logs), but expecting <= 4000. size/num main               Total
     Total    3334434/25659      3334434/25659
     Now      1960747/15815      1960747/15815
     Logspan  2:08:13.551        2:08:13.551
     Overhead 260645             359045

     Chattiest UIDs in main log buffer:                           Size   +/-  Pruned
     UID   PACKAGE                                               BYTES           NUM
     1000  system                                              1902780
     0     root                                                  39860

     Chattiest PIDs:                                              Size        Pruned
     ...

Change-Id: I307dd5aa5503db5ebf124b3b20ca6510dc002639